keys:
  - &Felix-yubikey 499C66E9512BA96797CDAC410562840F5B0C9BD4
  - &dienilles ca86ce346bdde0b88373f3c24a2744c2492ec4c8
creation_rules:
  - path_regex: nixos/secrets/.*
    key_groups:
    - pgp:
        - *Felix-yubikey
        - *dienilles
